# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6576aa65efcffb0f2f6d3ff8faf2fb0c8879e5d2ec98f3b3de71b2b469f23aa5514fd1c2e88f49132dadf89034dc0ae9dc0317b765c6dcd090744f5e7e062fca

test:
  secret_key_base: 9a6d5d49eaa6a80c29bfc76b048a07804f90610ddaf3fd1aac8df0fcf1b14b21c46413d7a854be4e1f419a0ff98068997f93cd44d9ccbe66594bc67366a58cc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
